apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prism0
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: prism0.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prism0
                port:
                  name: http
